export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
//Store Type
export const ADD_STORE = "ADD_STORE";
export const EDIT_STORE = "EDIT_STORE";
export const DELETE_STORE = "DELETE_STORE";
export const LIST_STORE = "LIST_STORE";
export const STORE_LOADING = "STORE_LOADING";
export const STORE_STOPLOADING = "STORE_STOPLOADING";

//Plan Type
export const ADD_PLAN = "ADD_PLAN";
export const EDIT_PLAN = "EDIT_PLAN";
export const DELETE_PLAN = "DELETE_PLAN";
export const LIST_PLAN = "LIST_PLAN";
export const PLAN_LOADING = "PLAN_LOADING";
export const PLAN_STOPLOADING = "PLAN_STOPLOADING";

//Slider Type
export const ADD_SLIDER = "ADD_SLIDER";
export const EDIT_SLIDER = "EDIT_SLIDER";
export const DELETE_SLIDER = "DELETE_SLIDER";
export const LIST_SLIDER = "LIST_SLIDER";
export const SLIDER_LOADING = "SLIDER_LOADING";
export const SLIDER_STOPLOADING = "SLIDER_STOPLOADING";

//CATEGORY Type
export const ADD_CATEGORY = "ADD_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const LIST_CATEGORY = "LIST_CATEGORY";
export const CATEGORY_LOADING = "CATEGORY_LOADING";
export const CATEGORY_STOPLOADING = "CATEGORY_STOPLOADING";

//SUBCATEGORY Type
export const ADD_SUBCATEGORY = "ADD_SUBCATEGORY";
export const EDIT_SUBCATEGORY = "EDIT_SUBCATEGORY";
export const DELETE_SUBCATEGORY = "DELETE_SUBCATEGORY";
export const LIST_SUBCATEGORY = "LIST_SUBCATEGORY";
export const SUBCATEGORY_LOADING = "SUBCATEGORY_LOADING";
export const SUBCATEGORY_STOPLOADING = "SUBCATEGORY_STOPLOADING";

//SUBCATEGORYCHILD Type
export const ADD_SUBCATEGORYCHILD = "ADD_SUBCATEGORYCHILD";
export const EDIT_SUBCATEGORYCHILD = "EDIT_SUBCATEGORYCHILD";
export const DELETE_SUBCATEGORYCHILD = "DELETE_SUBCATEGORYCHILD";
export const LIST_SUBCATEGORYCHILD = "LIST_SUBCATEGORYCHILD";
export const SUBCATEGORYCHILD_LOADING = "SUBCATEGORYCHILD_LOADING";
export const SUBCATEGORYCHILD_STOPLOADING = "SUBCATEGORYCHILD_STOPLOADING";

//PRODUCT Type
export const ADD_PRODUCT = "ADD_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const LIST_PRODUCT = "LIST_PRODUCT";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_STOPLOADING = "PRODUCT_STOPLOADING";

//User Type
export const ADD_USER = "ADD_USER";
export const EDIT_USER = "EDIT_USER";
export const DELETE_USER = "DELETE_USER";
export const LIST_USER = "LIST_USER";
export const USER_LOADING = "USER_LOADING";
export const USER_STOPLOADING = "USER_STOPLOADING";

//Author Type
export const ADD_AUTHOR = "ADD_AUTHOR";
export const EDIT_AUTHOR = "EDIT_AUTHOR";
export const DELETE_AUTHOR = "DELETE_AUTHOR";
export const LIST_AUTHOR = "LIST_AUTHOR";
export const AUTHOR_LOADING = "AUTHOR_LOADING";
export const AUTHOR_STOPLOADING = "AUTHOR_STOPLOADING";

//OrderStatus Type
export const ADD_ORDERSTATUS = "ADD_ORDERSTATUS";
export const EDIT_ORDERSTATUS = "EDIT_ORDERSTATUS";
export const DELETE_ORDERSTATUS = "DELETE_ORDERSTATUS";
export const LIST_ORDERSTATUS = "LIST_ORDERSTATUS";
export const ORDERSTATUS_LOADING = "ORDERSTATUS_LOADING";
export const ORDERSTATUS_STOPLOADING = "ORDERSTATUS_STOPLOADING";

//TEAM Type
export const ADD_TEAM = "ADD_TEAM";
export const EDIT_TEAM = "EDIT_TEAM";
export const DELETE_TEAM = "DELETE_TEAM";
export const LIST_TEAM = "LIST_TEAM";
export const TEAM_LOADING = "TEAM_LOADING";
export const TEAM_STOPLOADING = "TEAM_STOPLOADING";

//BLOG Type
export const ADD_BLOG = "ADD_BLOG";
export const EDIT_BLOG = "EDIT_BLOG";
export const DELETE_BLOG = "DELETE_BLOG";
export const LIST_BLOG = "LIST_BLOG";
export const BLOG_LOADING = "BLOG_LOADING";
export const BLOG_STOPLOADING = "BLOG_STOPLOADING";

//Shipping Type
export const ADD_SHIPPING = "ADD_SHIPPING";
export const EDIT_SHIPPING = "EDIT_SHIPPING";
export const DELETE_SHIPPING = "DELETE_SHIPPING";
export const LIST_SHIPPING = "LIST_SHIPPING";
export const SHIPPING_LOADING = "SHIPPING_LOADING";
export const SHIPPING_STOPLOADING = "SHIPPING_STOPLOADING";

//Coupon Type
export const ADD_COUPON = "ADD_COUPON";
export const EDIT_COUPON = "EDIT_COUPON";
export const DELETE_COUPON = "DELETE_COUPON";
export const LIST_COUPON = "LIST_COUPON";
export const COUPON_LOADING = "COUPON_LOADING";
export const COUPON_STOPLOADING = "COUPON_STOPLOADING";

//ORDER Type
export const ADD_ORDER = "ADD_ORDER";
export const EDIT_ORDER = "EDIT_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
export const LIST_ORDER = "LIST_ORDER";
export const ORDER_LOADING = "ORDER_LOADING";
export const ORDER_STOPLOADING = "ORDER_STOPLOADING";

//ROLE Type
export const ADD_ROLE = "ADD_ROLE";
export const EDIT_ROLE = "EDIT_ROLE";
export const DELETE_ROLE = "DELETE_ROLE";
export const LIST_ROLE = "LIST_ROLE";
export const ROLE_LOADING = "ROLE_LOADING";
export const ROLE_STOPLOADING = "ROLE_STOPLOADING";

//ADMIN Type
export const ADD_ADMIN = "ADD_ADMIN";
export const EDIT_ADMIN = "EDIT_ADMIN";
export const DELETE_ADMIN = "DELETE_ADMIN";
export const LIST_ADMIN = "LIST_ADMIN";
export const ADMIN_LOADING = "ADMIN_LOADING";
export const ADMIN_STOPLOADING = "ADMIN_STOPLOADING";

//PARENT ATTRIBUTE CATEGORY Type
export const ADD_PARENT_ATTRIBUTE_CATEGORY = "ADD_PARENT_ATTRIBUTE_CATEGORY";
export const EDIT_PARENT_ATTRIBUTE_CATEGORY = "EDIT_PARENT_ATTRIBUTE_CATEGORY";
export const DELETE_PARENT_ATTRIBUTE_CATEGORY =
  "DELETE_PARENT_ATTRIBUTE_CATEGORY";
export const LIST_PARENT_ATTRIBUTE_CATEGORY = "LIST_PARENT_ATTRIBUTE_CATEGORY";
export const PARENT_ATTRIBUTE_CATEGORY_LOADING =
  "PARENT_ATTRIBUTE_CATEGORY_LOADING";
export const PARENT_ATTRIBUTE_CATEGORY_STOPLOADING =
  "PARENT_ATTRIBUTE_CATEGORY_STOPLOADING";

//ATTRIBUTE CATEGORY Type
export const ADD_ATTRIBUTE_CATEGORY = "ADD_ATTRIBUTE_CATEGORY";
export const EDIT_ATTRIBUTE_CATEGORY = "EDIT_ATTRIBUTE_CATEGORY";
export const DELETE_ATTRIBUTE_CATEGORY = "DELETE_ATTRIBUTE_CATEGORY";
export const LIST_ATTRIBUTE_CATEGORY = "LIST_ATTRIBUTE_CATEGORY";
export const ATTRIBUTE_CATEGORY_LOADING = "ATTRIBUTE_CATEGORY_LOADING";
export const ATTRIBUTE_CATEGORY_STOPLOADING = "ATTRIBUTE_CATEGORY_STOPLOADING";

//ATTRIBUTE MAPPING Type
export const ADD_ATTRIBUTE_MAPPING = "ADD_ATTRIBUTE_MAPPING";
export const EDIT_ATTRIBUTE_MAPPING = "EDIT_ATTRIBUTE_MAPPING";
export const DELETE_ATTRIBUTE_MAPPING = "DELETE_ATTRIBUTE_MAPPING";
export const LIST_ATTRIBUTE_MAPPING = "LIST_ATTRIBUTE_MAPPING";
export const ATTRIBUTE_MAPPING_LOADING = "ATTRIBUTE_MAPPING_LOADING";
export const ATTRIBUTE_MAPPING_STOPLOADING = "ATTRIBUTE_MAPPING_STOPLOADING";

//PRODUCT SUB  Type
export const ADD_PRODUCTSUB = "ADD_PRODUCTSUB";
export const EDIT_PRODUCTSUB = "EDIT_PRODUCTSUB";
export const DELETE_PRODUCTSUB = "DELETE_PRODUCTSUB";
export const LIST_PRODUCTSUB = "LIST_PRODUCTSUB";
export const PRODUCTSUB_LOADING = "PRODUCTSUB_LOADING";
export const PRODUCTSUB_STOPLOADING = "PRODUCTSUB_STOPLOADING";

// Demo
export const ADD_PRODUCT_ID = "ADD_PRODUCT_ID";

export const ADD_ORDER_ATTRIBUTES = "ADD_ORDER_ATTRIBUTES";

export const ADD_ATTRIBUTE_PRICE = "ADD_ATTRIBUTE_PRICE";
export const ADD_ATTRIBUTE_ITEM = "ADD_ATTRIBUTE_ITEM";
export const REMOVE_ATTRIBUTE_ITEM = "REMOVE_ATTRIBUTE_ITEM";

export const SEARCH_PRODUCT_REQUEST = "SEARCH_PRODUCT_REQUEST";
export const SEARCH_PRODUCT_SUCCESS = "SEARCH_PRODUCT_SUCCESS";
export const SEARCH_PRODUCT_FAIL = "SEARCH_PRODUCT_FAIL";
